version: '3'

services:
  app:
    build: .
    container_name: contentful_explorer_app
    env_file:
      - .docker.env
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=dummy
      - DATABASE_PASSWORD=my-super-secret-password
      - DATABASE_NAME=contentful_explorer
      - PORT=3000
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: contentful_explorer_db
    restart: always
    environment:
      POSTGRES_USER: dummy
      POSTGRES_PASSWORD: my-super-secret-password
      POSTGRES_DB: contentful_explorer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
