export const ConfigKey = {
  PORT: 'PORT',
  DATABASE_HOST: 'DATABASE_HOST',
  DATABASE_PORT: 'DATABASE_PORT',
  DATABASE_USER: 'DATABASE_USER',
  DATABASE_PASSWORD: 'DATABASE_PASSWORD',
  DATABASE_NAME: 'DATABASE_NAME',
  DATABASE_LOGGING: 'DATABASE_LOGGING',
  CONTENTFUL_SPACE_ID: 'CONTENTFUL_SPACE_ID',
  CONTENTFUL_ACCESS_TOKEN: 'CONTENTFUL_ACCESS_TOKEN',
  CONTENTFUL_ENVIRONMENT: 'CONTENTFUL_ENVIRONMENT',
  CONTENTFUL_CONTENT_TYPE: 'CONTENTFUL_CONTENT_TYPE',
  JWT_SECRET: 'JWT_SECRET',
};
